#ifndef CONSTANT_H
#define CONSTANT_H

#define WINDOW_LENGTH 1100
#define WINDOW_WIDTH 910

#define GRID_EDGE_WIDTH 2
#define GRID_SEPARATOR_WIDTH 1

#define TILE_WIDTH 20
#define TILE_NUMBER 40

#define GRID_MARGIN 25
#define GRID_WIDGET_WIDTH (TILE_WIDTH * TILE_NUMBER + 2 * GRID_MARGIN)
#define GRID_SHIFT 30

#define FOOD_WIDTH 16
#define FOOD_INTERVAL ((TILE_WIDTH - FOOD_WIDTH) / 2)

#define SNAKE_WIDTH 16
#define SNAKE_INTERVAL ((TILE_WIDTH - SNAKE_WIDTH) / 2)

#define OBSTACLE_WIDTH 16
#define OBSTACLE_INTERVAL ((TILE_WIDTH - OBSTACLE_WIDTH) / 2)

#define BOARD_BTN_INTERVAL 0

#define SNAKE_GROWTH 3

#define CAPTION_Y_SHIFT 30

#define CAPTION_CENTRAL_LOCATION (GRID_SHIFT + TILE_WIDTH * TILE_NUMBER / 2)
#define CAPTION_LENGTH 800
#define CAPTION_WIDTH 100
#define CAPTION_START_X (CAPTION_CENTRAL_LOCATION - CAPTION_LENGTH / 2)
#define CAPTION_START_Y (CAPTION_CENTRAL_LOCATION - CAPTION_WIDTH / 2 - CAPTION_Y_SHIFT)

#define CAPTION_SIZE 90

#define DEATH_CAPTION_LENGTH 1000
#define DEATH_CAPTION_WIDTH 30
#define DEATH_CAPTION_START_X (CAPTION_START_X - (DEATH_CAPTION_LENGTH - CAPTION_LENGTH) / 2)
#define DEATH_CAPTION_START_Y (CAPTION_START_Y + CAPTION_WIDTH)

#define DEATH_CAPTION_SIZE 20

#define TITLE_SIZE 18
#define SUB_TITLE_SIZE 16
#define NUMBER_SIZE 14

#define TIMER_INTERVAL 70

#define SAFE_RANGE_START 10
#define SAFE_RANGE_END (TILE_NUMBER - SAFE_RANGE_START)

#define SCORE_PER_FOOD 5

#define BTN_LENGTH 140
#define BTN_WIDTH 40
#define BTN_INTERVAL 10

#define SCORE_BOARD_LENGTH 200
#define SCORE_BOARD_WIDTH 100

#endif // CONSTANT_H
